apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-backend
  namespace: reddit-async                # 指定命名空间
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit-backend
  template:
    metadata:
      labels:
        app: reddit-backend
    spec:
      containers:
      - name: reddit-backend
        image: morningeatdinner/reddit-backend:v0.6 # 替换为你的镜像名称和版本
        ports:
        - containerPort: 9000         # 替换为你的应用程序端口
---
apiVersion: v1
kind: Service
metadata:
  name: reddit-backend-service
  namespace: reddit-async                # 指定命名空间
spec:
  selector:
    app: reddit-backend                   # 与 Deployment 中的 app 标签一致
  type: NodePort                      # 可以用 NodePort 或 ClusterIP，根据需求更改
  ports:
    - protocol: TCP
      port: 9000                           # Service 暴露的端口
      targetPort: 9000                     # 应用程序容器的端口（与 containerPort 一致）
