name: build

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: morningeatdinner

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build reddit and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/reddit-backend:${{ steps.vars.outputs.sha_short }}
      - name: Update helm values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/values.yaml'
          commitChange: true
          branch: main
          message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
          changes: |
            {
              "deploy.tag": "${{ steps.vars.outputs.sha_short }}"
            }